# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-15 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_buy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_comment', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DealedProduct',
            fields=[
                ('dealed_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_product_dealed', models.IntegerField()),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_product_order', models.IntegerField()),
                ('bill', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='FlashProduct',
            fields=[
                ('flashproduct', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('flash_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_flash', models.DateTimeField()),
                ('end_flash', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=255)),
                ('hdh', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('CPU', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('pay_type', models.IntegerField(default=0)),
                ('gurantee', models.CharField(max_length=255)),
                ('promotion', models.IntegerField()),
                ('start_promo', models.DateTimeField()),
                ('end_promo', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transporter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='transporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Transporter'),
        ),
        migrations.AddField(
            model_name='flashproduct',
            name='flashsale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.FlashSale'),
        ),
        migrations.AddField(
            model_name='flashproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='detailorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product'),
        ),
        migrations.AddField(
            model_name='dealedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Staff'),
        ),
        migrations.AddField(
            model_name='bill',
            name='status_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.StatusProduct'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
